#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
RED='\033[0;31m'
PURPLE='\033[1;35m' # No Purple

go test ./app -v
if [ ! $? = 0 ]; then
	echo >&2 "${PURPLE} Unit test ${RED}failed"
	exit 1
fi
exit 0
